{{- if .Values.drhpc.enabled }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: oci-lens-dr-hpc
  namespace: {{ .Values.namespace.name }}
  labels:
    app: oci-lens-dr-hpc
    component: gpu-monitoring
spec:
  selector:
    matchLabels:
      app: oci-lens-dr-hpc
  template:
    metadata:
      labels:
        app: oci-lens-dr-hpc
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: amd.com/gpu
                operator: In
                values: ["true", "present"]
      
      tolerations:
      - key: amd.com/gpu
        operator: Exists
        effect: NoSchedule

      priorityClassName: system-node-critical
      terminationGracePeriodSeconds: 0
      
      volumes: 
      - name: root
        hostPath:
          path: "/"
      
      hostPID: true
      hostIPC: true
      hostNetwork: true
      
      containers:
      - name: oke-dr-hpc-prod
        image: "{{ .Values.global.ociImageRegistry }}/{{ .Values.drhpc.image.repository }}:{{ .Values.drhpc.image.tag }}"
        imagePullPolicy: {{ .Values.drhpc.image.pullPolicy }}
        
        securityContext:
          privileged: true
          capabilities:
            add: [SYS_ADMIN]
        
        volumeMounts: 
        - name: root
          mountPath: /host
        
        resources: {}
        
        env:
        - name: PUSH_GATEWAY
          value: {{ .Values.global.pushGatewayUrl | quote }}
        - name: JOB_NAME
          value: "oci_lens_drhpc_metrics"
{{- end }}