# Global configuration
global:
  namespace: oci-gpu-scanner-plugin
  pushGatewayUrl: "http://prometheus-pushgateway:9091/"
  ociImageRegistry: iad.ocir.io/iduyx1qnmway/lens-metric-collector

# Namespace configuration
namespace:
  create: false
  name: oci-gpu-scanner-plugin

# Go Plugin configuration
goPlugin:
  enabled: true
  image:
    repository: oci_lens_metric_collector
    tag: v0.0.9
    pullPolicy: Always
  
  config:
    gpuType: "amd"
    pushFrequency: "10"
    jobName: "oci_lens_node_metrics"
    maxPasses: "0"
    sleepSecs: "10"
    logLevel: "info"
    logFormat: "json"
  
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# AMD GPU Exporter
amdGpuExporter:
  enabled: true
  global:
    imageRegistry: ""
  image:
    repository: docker.io/rocm/device-metrics-exporter
    tag: v1.3.1
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Metrics Push Job
metricsPushJob:
  enabled: true
  schedule: "* * * * *"
  
  resources:
    requests:
      memory: "32Mi"
      cpu: "50m"
    limits:
      memory: "64Mi"
      cpu: "100m"

# Active Health Check
healthCheck:
  enabled: false
  image:
    repository: oci_lens_healthcheck_amd
    tag: v0.0.2
    pullPolicy: Always
  
  resources:
    requests:
      memory: "8Gi"
      cpu: "2"
    limits:
      memory: "16Gi"
      cpu: "4"

# DRHPC
drhpc:
  enabled: true
  image:
    repository: oci_lens_drhpc_amd
    tag: v0.0.1
    pullPolicy: Always

# RBAC
rbac:
  create: true

# Node Exporter
nodeExporter:
  enabled: true
  
# Override default values for the official chart
prometheus-node-exporter:
  image:
    registry: "quay.io"
    repository: prometheus/node-exporter
    tag: v1.8.2
    pullPolicy: IfNotPresent
  hostRootFsMount:
    enabled: true
  hostNetwork: true
  hostPID: true
  extraArgs:
    - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    - --collector.filesystem.fs-types-exclude=^(sys|proc|auto)fs$$
    - --web.max-requests=40
    - --no-collector.systemd
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Pod Node Mapper
podNodeMapper:
  enabled: true
  replicas: 1
  image:
    repository: oci_lens_pod_node_info
    tag: latest
    pullPolicy: Always
  
  # Configuration
  jobName: "oci_lens_pod_metrics"
  clusterName: "oci-lens-cluster"  # Update this per cluster
  
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"