{
 "title": "OCI Lens - Demo Pool H100 & MI300X Monitoring Ring",
 "description": "GPU health monitoring dashboard for Demo Pool H100 & MI300X monitoring ring. OCI lens checks the readiness of GPUs, RDMA network and invokes active performance checks while enabling continuous monitoring.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ociregion", "label": "OCI Region", "query": { "query": "" } },
   { "name": "hostshape", "label": "GPU Type", "query": { "query": "" } },
   { "name": "hostname", "label": "Host Name", "query": { "query": "" } },
   {
    "name": "k8sworkload",
    "label": "Kubernetes Worklaod",
    "query": {
     "query": "label_values(oci_lens_pod_node_info{workload_type=\"Deployment\"},workload)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# OCI Lens - GPU Host Health Monitoring\nPer node health data with node health, GPU health, RDMA health"
   }
  },
  {
   "title": "Host Node Metadata",
   "type": "table",
   "description": "All details of the host",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "oci_lens_host_metadata{instance=~\"$hostname\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OCI Dr.HPC Health Check Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"final_status\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"gpu_count\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"gpu_mode_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"gpu_clk_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"gpu_xid_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"gpu_width_count\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"gpu_speed_count\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"pcie_error_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"pcie_speed\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"pcie_width\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"max_acc_out\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"max_acc_adv_settings\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"gid_index_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"sram_error_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"row_remap_error_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"nvlink_speed_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"nvlink_inactive_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"rdma_link_flap_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"rdma_nic_count\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"rdma_width_count\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"rdma_speed_count\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"hca_error_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"link_down_state\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"rx_discards_status\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"auth_status\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"eth0_presence_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"hpc_info_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"missing_interface_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"peermem_module_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"cdfp_cable_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"fabricmanager_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"thermal_throttling_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"source_based_routing_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"oca_version_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"drhpc_rttcc_status\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"drhpc_failure_recommendation\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OCI Active Performance Checks",
   "type": "table",
   "description": "GPU & Host Performance Summary",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"compute_throughput\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"memory_bandwidth\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"error_detection\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"tensor_core_utilization\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"sustained_workload\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"mixed_precision_testing\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"background_computation\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"model_mfu\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"gpu_temperature_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"gpu_power_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"gpu_utilization_check\", instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ACTIVE HEALTH PERFORMANCE DATA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last node HBM throughput b/w ",
     "type": "gauge",
     "description": "HBM BW",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oci_lens_compute_throughput_total_bandwidth_gbps{hostname=~\"$hostname\"}",
       "legendFormat": "{{HostName}}"
      }
     ]
    },
    {
     "title": "Avg model flops achieved by node",
     "type": "gauge",
     "description": "Flops utilizations by GPU and by Node",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(oci_lens_model_mfu_achieved_tflops{hostname=~\"$hostname\"}) by (HostName)",
       "legendFormat": "{{HostName}}"
      }
     ]
    },
    {
     "title": "Avg RDMA Packets Sent B/W",
     "type": "gauge",
     "description": "RDMA Bandwidth by node",
     "gridPos": { "h": 8, "w": 13, "x": 10, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(oci_lens_rdma_np_cnp_sent{hostname=~\"$hostname\"}) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU & RDMA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_TEMP{Hostname=~\"$hostname\"} OR gpu_junction_temperature{hostname=~\"$hostname\"}",
       "legendFormat": "GPU {{gpu}}{{gpu_id}} - {{Hostname}}{{hostname}}"
      }
     ]
    },
    {
     "title": "GPU Power Total Consumed",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 13, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "avg(DCGM_FI_DEV_POWER_USAGE{Hostname=~\"$hostname\"} OR gpu_power_usage{hostname=~\"$hostname\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Avg. Temp",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(DCGM_FI_DEV_GPU_TEMP{Hostname=~\"$hostname\"} OR gpu_junction_temperature{hostname=~\"$hostname\"}) ",
       "legendFormat": "Avg GPU Temperature"
      }
     ]
    },
    {
     "title": "GPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"} OR gpu_gfx_activity{hostname=~\"$hostname\"})",
       "legendFormat": "{{Hostname}}{{hostname}}"
      }
     ]
    },
    {
     "title": "GPU Power Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_POWER_USAGE{Hostname=~\"$hostname\"} OR gpu_power_usage{hostname=~\"$hostname\"}",
       "legendFormat": "GPU {{gpu}}{{gpu_id}} - {{Hostname}}{{hostname}}"
      }
     ]
    },
    {
     "title": "Tensor Core Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{Hostname=~\"$hostname\"} OR gpu_prof_tensor_active_percent{hostname=~\"$hostname\"}",
       "legendFormat": "GPU {{gpu}}{{gpu_id}} - {{Hostname}}{{hostname}} "
      }
     ]
    }
   ]
  },
  {
   "title": "NODE HEALTH METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "((node_filesystem_size_bytes{device!~\"rootfs\",instance=~\"${hostname:regex}\"} - node_filesystem_avail_bytes{device!~\"rootfs\",instance=~\"${hostname:regex}\"}) / node_filesystem_size_bytes{ device!~\"rootfs\",instance=~\"${hostname:regex}\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk IO",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"${hostname:regex}\"}[2m])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Hardware Temperature Monitor",
     "type": "timeseries",
     "description": "Monitors hardware sensor temperatures and critical thresholds as exposed by Linux hwmon. Includes CPU, GPU, and motherboard sensors where available",
     "gridPos": { "h": 50, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "node_hwmon_temp_celsius * on(chip, instance) group_left(chip_name) node_hwmon_chip_names{instance=~\"${hostname:regex}\"}",
       "legendFormat": "{{ instance }}  {{ chip_name }} {{ sensor }}"
      }
     ]
    },
    {
     "title": "CPU Pressure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "rate(node_pressure_memory_waiting_seconds_total{job=\"oci_lens_node_exporter\",instance=~\"${hostname:regex}\"}[2m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{ mode=\"system\",instance=~\"${hostname:regex}\"}[2m])) / scalar(count(count(node_cpu_seconds_total{instance=~\"${hostname:regex}\"}) by (cpu)))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}