{{- if .Values.drhpc.enabled }}
{{- range .Values.drhpc.gpuTypes }}
{{- if .enabled }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: oci-lens-dr-hpc-{{ .type }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    app: oci-lens-dr-hpc-{{ .type }}
    component: gpu-monitoring
spec:
  selector:
    matchLabels:
      app: oci-lens-dr-hpc-{{ .type }}
  template:
    metadata:
      labels:
        app: oci-lens-dr-hpc-{{ .type }}
        gpu-type: {{ .type }}
    spec:
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      priorityClassName: system-node-critical
      terminationGracePeriodSeconds: 0
      
      volumes: 
      - name: root
        hostPath:
          path: "/"
      - name: drhpc-results
        hostPath:
          path: {{ .resultsHostPath | default "/var/lib/oci-dr-hpc-v2" | quote }}
          type: DirectoryOrCreate
      
      hostPID: true
      hostIPC: true
      hostNetwork: true
      
      containers:
      - name: oke-dr-hpc-prod
        {{- if eq .type "nvidia" }}
        # NVIDIA: oci-dr-hpc-v2:cuda-12.9.0-latest
        image: "{{ $.Values.global.ociImageRegistry }}/{{ .image.repository }}:{{ .image.cudaVersion }}-{{ .image.tag }}"
        {{- else }}
        # AMD: oci-dr-hpc-v2:rocm-latest
        image: "{{ $.Values.global.ociImageRegistry }}/{{ .image.repository }}:{{ .image.rocmVersion }}-{{ .image.tag }}"
        {{- end }}
        imagePullPolicy: {{ .image.pullPolicy | default "Always" }}
        
        securityContext:
          privileged: true
          capabilities:
            add: 
            - SYS_ADMIN
        
        volumeMounts: 
        - name: root
          mountPath: /host
        - name: drhpc-results
          mountPath: /opt/oci-hpc/oci-dr-hpc
        
        # Same resource config for both AMD and NVIDIA
        resources:
          {{- toYaml .resources | nindent 10 }}
        
        env:
        - name: PUSH_GATEWAY
          value: {{ $.Values.global.pushGatewayUrl | quote }}
        - name: JOB_NAME
          value: "oci_lens_drhpc_metrics"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {{- if eq .type "nvidia" }}
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        {{- else }}
        # AMD environment variables
        - name: ROCR_VISIBLE_DEVICES
          value: "all"
        - name: HSA_OVERRIDE_GFX_VERSION
          value: "11.0.0"
        {{- end }}
        {{- with .extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
{{- end }}
{{- end }}