apiVersion: v2
name: oci-gpu-scanner-plugin
description: OCI Scanner Plugin for AMD and Nvidia GPU monitoring and health checks
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - oci
  - amd
  - gpu
  - monitoring
  - prometheus
home: https://github.com/oracle/oci-lens-quickstart
maintainers:
  - name: OCI Lens Team
    email: amar.gowda@oracle.com

dependencies:
# Prometheus Node Exporter
  - name: prometheus-node-exporter
    version: 4.40.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: nodeExporter.enabled
 
  # NVIDIA DCGM Exporter
  - name: dcgm-exporter
    version: 4.5.2
    repository: https://nvidia.github.io/dcgm-exporter/helm-charts
    condition: nvidiaGpuExporter.enabled
  
  # Rocm Device Metrics Exporter
  - name: device-metrics-exporter-charts  
    version: "1.4.0"
    repository: "https://rocm.github.io/device-metrics-exporter/"
    condition: amdGpuExporter.enabled