{
 "title": "OCI GPU Scanner - OKE to Scanner Tracking Board - JCHEUNG 2",
 "description": "GPU health monitoring dashboard for OKE workloads to GPU health checks mapping boards.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ociregion", "label": "OCI Region", "query": { "query": "" } },
   { "name": "hostshape", "label": "GPU Type", "query": { "query": "" } },
   {
    "name": "k8snamespace",
    "label": "Kubernetes Namespace",
    "query": {
     "query": "label_values(oci_lens_pod_node_info,namespace)"
    }
   },
   {
    "name": "k8sworkload",
    "label": "Kubernetes Workload",
    "query": {
     "query": "label_values(oci_lens_pod_node_info{namespace=~\"$k8snamespace\"},workload)"
    }
   },
   {
    "name": "node",
    "label": "Node Name",
    "query": {
     "query": "label_values(oci_lens_pod_node_info{workload=~\"$k8sworkload\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "HEALTH SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Host Node Metadata",
   "type": "table",
   "description": "All details of the host",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "oci_lens_host_metadata{instance=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OCI GPU Scanner - PASSIVE health check summary",
   "type": "table",
   "description": "Dr HPC V2 based passive checks scan results",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"final_status\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"gpu_count\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"gpu_mode_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"gpu_clk_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"gpu_xid_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"gpu_width_count\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"gpu_speed_count\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"pcie_error_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"pcie_speed\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"pcie_width\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"max_acc_out\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"max_acc_adv_settings\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"gid_index_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"sram_error_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"row_remap_error_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"nvlink_speed_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"nvlink_inactive_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"rdma_link_flap_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"rdma_nic_count\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"rdma_width_count\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"rdma_speed_count\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"hca_error_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"link_down_state\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"rx_discards_status\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"auth_status\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"eth0_presence_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"hpc_info_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"missing_interface_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"peermem_module_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"cdfp_cable_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"fabricmanager_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"thermal_throttling_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"source_based_routing_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"oca_version_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"drhpc_rttcc_status\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_drhpc_node_summary{test=\"drhpc_failure_recommendation\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OCI GPU Scanner - ACTIVE health check summary",
   "type": "table",
   "description": "Active checks performance health check results",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"compute_throughput\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"memory_bandwidth\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"error_detection\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"tensor_core_utilization\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"sustained_workload\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"mixed_precision_testing\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"background_computation\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"model_mfu\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"gpu_temperature_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"gpu_power_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oci_lens_healthcheck_node_summary{test=\"gpu_utilization_check\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (instance) (push_time_seconds{job=\"oci_lens_healthchecks\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ACTIVE HEALTH PERFORMANCE DATA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Last node HBM throughput b/w ",
   "type": "gauge",
   "description": "HBM BW",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oci_lens_compute_throughput_total_bandwidth_gbps{hostname=~\"$node\"}",
     "legendFormat": "{{HostName}}"
    }
   ]
  },
  {
   "title": "Avg model flops achieved by node",
   "type": "gauge",
   "description": "Flops utilizations by GPU and by Node",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(oci_lens_model_mfu_achieved_tflops{hostname=~\"$node\"}) by (HostName)",
     "legendFormat": "{{HostName}}"
    }
   ]
  },
  {
   "title": "Avg RDMA Packets Sent B/W",
   "type": "gauge",
   "description": "RDMA Bandwidth by node",
   "gridPos": { "h": 8, "w": 13, "x": 10, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(oci_lens_rdma_np_cnp_sent{hostname=~\"$node\"}) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "GPU & RDMA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{Hostname=~\"$node\"} OR (label_replace(amd_gpu_junction_temperature, \"node\", \"$1\", \"hostname\", \"(.+)\") * on(node) group_left(hostname) (max by(node, hostname) (oci_lens_pod_node_info{node=~\"$node\"})))",
     "legendFormat": "GPU {{gpu}}{{gpu_id}} - {{Hostname}}{{node}}"
    }
   ]
  },
  {
   "title": "GPU Power Total Consumed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_POWER_USAGE{Hostname=~\"$node\"} OR (label_replace(amd_gpu_package_power, \"node\", \"$1\", \"hostname\", \"(.+)\") * on(node) group_left(hostname) (max by(node, hostname) (oci_lens_pod_node_info{node=~\"$node\"}))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{Hostname=~\"$node\"} OR (label_replace(amd_gpu_junction_temperature, \"node\", \"$1\", \"hostname\", \"(.+)\") * on(node) group_left(hostname) (max by(node, hostname) (oci_lens_pod_node_info{node=~\"$node\"})))) ",
     "legendFormat": "Avg GPU Temperature"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$node\"} OR (label_replace(amd_gpu_gfx_activity, \"node\", \"$1\", \"hostname\", \"(.+)\") * on(node) group_left(hostname) (max by(node, hostname) (oci_lens_pod_node_info{node=~\"$node\"}))))",
     "legendFormat": "{{Hostname}}{{node}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{Hostname=~\"$node\"} OR (label_replace(amd_gpu_package_power, \"node\", \"$1\", \"hostname\", \"(.+)\") * on(node) group_left(hostname) (max by(node, hostname) (oci_lens_pod_node_info{node=~\"$node\"})))",
     "legendFormat": "GPU {{gpu}}{{gpu_id}} - {{Hostname}}{{node}}"
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{Hostname=~\"$node\"} OR amd_prof_tensor_active_percent{node=~\"$node\"}",
     "legendFormat": "GPU {{gpu}}{{gpu_id}} - {{Hostname}}{{hostname}} "
    }
   ]
  },
  { "title": "NODE HEALTH METRICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{device!~\"rootfs\",node=~\"${node:regex}\"} - node_filesystem_avail_bytes{device!~\"rootfs\",node=~\"${node:regex}\"}) / node_filesystem_size_bytes{ device!~\"rootfs\",node=~\"${node:regex}\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{node=~\"${node:regex}\"}[2m])",
     "legendFormat": "{{node}} {{device}}"
    }
   ]
  },
  {
   "title": "Hardware Temperature Monitor",
   "type": "timeseries",
   "description": "Monitors hardware sensor temperatures and critical thresholds as exposed by Linux hwmon. Includes CPU, GPU, and motherboard sensors where available",
   "gridPos": { "h": 32, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius * on(chip, node) group_left(chip_name) node_hwmon_chip_names{node=~\"${node:regex}\"}",
     "legendFormat": "{{ node }}  {{ chip_name }} {{ sensor }}"
    }
   ]
  },
  {
   "title": "CPU Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "rate(node_pressure_memory_waiting_seconds_total{node=~\"${node:regex}\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{ mode=\"system\",node=~\"${node:regex}\"}[2m])) / scalar(count(count(node_cpu_seconds_total{node=~\"${node:regex}\"}) by (cpu)))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}